In [3]:
import numpy as np
import pandas as pd
df = pd.DataFrame(
   np.random.randn(1000, 2) / [50, 50] + [-23.5505, -46.6333],
   columns=['lat', 'lon'])  
df

           lat        lon
0   -23.541375 -46.624505
1   -23.538625 -46.654364
2   -23.564114 -46.657255
3   -23.569455 -46.626086
4   -23.603828 -46.627085
..         ...        ...
995 -23.551020 -46.661792
996 -23.550458 -46.644185
997 -23.517279 -46.659157
998 -23.581526 -46.636410
999 -23.569295 -46.663440

[1000 rows x 2 columns]

In [4]:
pd.read_csv('coordenadas.csv')

         lat        lon
0 -23.561356 -46.656518
1 -23.587289 -46.657579
2 -23.541302 -46.629391
3 -23.535800 -46.633469

In [11]:
import requests
import time
import random

# URL do seu endpoint Flask para receber coordenadas
URL_ENDPOINT = "http://127.0.0.1:5000/nova-coordenada"

# Coordenadas aproximadas da região de São Paulo
LAT_MIN = -23.7
LAT_MAX = -23.4
LON_MIN = -46.8
LON_MAX = -46.5

# Loop infinito para enviar requisições
while True:
    try:
        # Gera uma coordenada aleatória dentro da área de São Paulo
        latitude_aleatoria = random.uniform(LAT_MIN, LAT_MAX)
        longitude_aleatoria = random.uniform(LON_MIN, LON_MAX)

        # Dados a serem enviados no corpo da requisição
        dados = {
            "latitude": latitude_aleatoria,
            "longitude": longitude_aleatoria
        }

        # Envia a requisição POST para o servidor Flask
        response = requests.post(URL_ENDPOINT, json=dados)

        # Verifica se a requisição foi bem-sucedida
        if response.status_code == 200:
            print(f"Requisição enviada com sucesso para: ({latitude_aleatoria:.4f}, {longitude_aleatoria:.4f})")
        else:
            print(f"Erro ao enviar requisição. Código de status: {response.status_code}")
            print(f"Resposta do servidor: {response.text}")

    except requests.exceptions.RequestException as e:
        print(f"Erro de conexão: {e}")
        
    # Espera 1 segundo antes de enviar a próxima requisição
    time.sleep(1)

Requisição enviada com sucesso para: (-23.5656, -46.5708)
Requisição enviada com sucesso para: (-23.4724, -46.6871)
Requisição enviada com sucesso para: (-23.6890, -46.5738)
Requisição enviada com sucesso para: (-23.5175, -46.7648)
Requisição enviada com sucesso para: (-23.6262, -46.6003)
Requisição enviada com sucesso para: (-23.4386, -46.5434)
Requisição enviada com sucesso para: (-23.4340, -46.5770)
Requisição enviada com sucesso para: (-23.5603, -46.6776)
Requisição enviada com sucesso para: (-23.4143, -46.5624)
Requisição enviada com sucesso para: (-23.4524, -46.7035)
Requisição enviada com sucesso para: (-23.6372, -46.7959)
Requisição enviada com sucesso para: (-23.4872, -46.5817)
Requisição enviada com sucesso para: (-23.6476, -46.6485)
Requisição enviada com sucesso para: (-23.6946, -46.7613)
Requisição enviada com sucesso para: (-23.5086, -46.6629)
Requisição enviada com sucesso para: (-23.5820, -46.6948)
Requisição enviada com sucesso para: (-23.6374, -46.5895)
Requisição enviada com sucesso para: (-23.6378, -46.7246)
Requisição enviada com sucesso para: (-23.4531, -46.5533)
Requisição enviada com sucesso para: (-23.5312, -46.5007)
Requisição enviada com sucesso para: (-23.4245, -46.5890)
Requisição enviada com sucesso para: (-23.5850, -46.7220)
Requisição enviada com sucesso para: (-23.4338, -46.6168)
Requisição enviada com sucesso para: (-23.5683, -46.6087)
Requisição enviada com sucesso para: (-23.6512, -46.5047)
Requisição enviada com sucesso para: (-23.4066, -46.6302)
Requisição enviada com sucesso para: (-23.5077, -46.6225)
Requisição enviada com sucesso para: (-23.6054, -46.5973)
Requisição enviada com sucesso para: (-23.5683, -46.5623)
Requisição enviada com sucesso para: (-23.4060, -46.6720)
Requisição enviada com sucesso para: (-23.6561, -46.5810)
Requisição enviada com sucesso para: (-23.5503, -46.5332)
Requisição enviada com sucesso para: (-23.4087, -46.5757)

KeyboardInterrupt: